### PR TITLE
Bugfix: Sub schemas

### PR DESCRIPTION
**Pull request by znicholasbrown**
This PR removes `maxLevel` considerations for schema properties and ignores meta-defined rendering in favor of a property-first version that falls back to the same component.

Closes https://github.com/PrefectHQ/prefect/issues/7816

### CODE REVIEW

**Review by pleek91 — APPROVED** [review]
Seems like a logical fix. Makes me wonder if this is going to brake some other edge case though. But I cannot think of a specific case to test for.

**Comment by zhen0** [comment]
Looks like it fixes the issue for me:

image

**Comment by zhen0** [comment]
Could we link the relevant issue in the description so it gets closed: https://github.com/PrefectHQ/prefect/issues/7816

**Comment by pleek91** [comment]
closes https://github.com/PrefectHQ/prefect/issues/7816

**Comment by znicholasbrown** [comment]
Throwing a DNM label on this; @pleek91 and I chatted through this change and decided we want to lean into it further by removing max-level limitations as well. Will ask for re-approval once that's done (should be today)

**Review by pleek91 — APPROVED** [review]
Thanks @znicholasbrown !

**Pull request merged**
