### PR TITLE
Feature: subscription interval provide/inject using `useInterval`

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Adds a new injection key and composition for injecting the interval for a subscription. This means at the component level we can provide default polling per implementation without having to prop drill. This is specifically being implemented for the workspace dashboard were we want the whole page to poll at a specific interval.

### CODE REVIEW

**Review by brandonreid — APPROVED** [review]

**Comment by pleek91** [comment]
@znicholasbrown I'd also like your eyes on this from a pattern perspective. Might be some risk you see that I didn't think of.

**Review by znicholasbrown — APPROVED** [review]
I think this is fine - the only issue I forsee is the lack of granularity; any subscription that relies on the injection necessarily has the same interval, which fits the dashboard use case but isn't particularly flexible elsewhere (or even on the dashboard if groups of components needed to refresh at different intervals but still want to avoid the drilling piece)

**Comment by pleek91** [comment]
@znicholasbrown my thought being generally we want all subscriptions within a card/list item/page to interval at the same rate. So this provides a way to set that interval at any level. I think this still allows for a component to have a dedicated interval if needed but generally we haven't needed that.

**Comment by znicholasbrown** [comment]
Hm ok yeah generally agreed and this is a marked improvement regardless 👍🏻

**Pull request merged**
