### PR TITLE
Enhancement: Organize and update task run details

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Closes https://github.com/PrefectHQ/prefect/issues/8632

### CODE REVIEW

**Review by znicholasbrown — APPROVED** [review]
Approving in case it's intentional but it looks like this removes the Cache Key line

**Review by znicholasbrown — APPROVED** [review]
Approving in case it's intentional but it looks like this removes the Cache Key line

**Review by znicholasbrown — APPROVED** [review]
Approving in case it's intentional but it looks like this removes the Cache Key line

**Comment by pleek91** [comment]
@znicholasbrown Cache Key is still visible it was just moved. TY!

**Pull request merged**
