### PR TITLE
BugFix: Flow run timeline doesn't react to route changes

### PR DESCRIPTION
**Pull request by pleek91**
# Description
There was a reactivity issue in the FlowRunTimeline component which caused it to not update when `props.flowRun` was changed. Passing a computed flow run id into the subscription rather than `props.flowRun.id` fixes that. 

Also implemented the `useStatePolling` composition to prevent this from polling longer than it should

@brandonreid I tested this but it would be great if you could also test this. You would probably catch if something unexpected is happening. 

Closes https://github.com/PrefectHQ/prefect-ui-library/issues/1269

### CODE REVIEW

**Review by znicholasbrown — COMMENTED** [review]
This looks ok to me but would love if @brandonreid could give the final sign off

**Comment by brandonreid** [comment]
I've got this tab open and will totally scope it out when demo stuff is done. Really appreciate you picking this up!

**Comment by brandonreid** [comment]
So testing this locally, it doesn't appear to clear the graph and redraw with just the sub-flow data. I may not have it setup properly, but even still, I know that the graph is not quite setup to manage new, completely different data. This is in part for performance, so it can cache already drawn things and add new ones when a flow run is running. I had operated under the assumption that new data would trigger a remount. Without pretty significant changes in the graphs repo, some efforts to check the tree and cleanup no-longer existing nodes, etc. the fastest and most simple route is likely to remount the graph when the route changes.

If this actually works for you and I'm somehow mistaken there, then heck yeah.

**Comment by pleek91** [comment]
ah I see 
image

Probably something internal to the chart we can update to fix that. Caching makes sense but it seems like the ability to remove nodes from the graph isn't taken into consideration. 

This reactivity fix is valid and necessary. But until we fix that this cannot be merged. So I'm going to close this and make a note on the original issue.

**Pull request closed without merging**
