### PR TITLE
add ability to filter FlowList by has deployment or not

### PR DESCRIPTION
**Pull request by brandonreid**
Related to https://github.com/PrefectHQ/prefect/issues/9517

I temporarily enabled this screen and linked it up locally for testing in staging:

https://github.com/PrefectHQ/prefect-ui-library/assets/6776415/0bc7e0f2-9214-42c3-9542-b859efdac554

### CODE REVIEW

**Comment by pleek91** [comment]
I could be wrong but isn't this page turned off in prod? Like don't users see the flows table still?

**Comment by brandonreid** [comment]
> I could be wrong but isn't this page turned off in prod? Like don't users see the flows table still?

In Nebula, that's correct, but in OSS we actually use this page and still have the separate Deployments page. Idk why exactly.. This functionality should probably be in Nebula as well though, now that you mention it.. So I won't call this ticket resolved quite yet.

**Comment by znicholasbrown** [comment]
That screen should probably be hidden altogether in OSS in favor of the existing deployments/flows since it's been removed from the cloud env; if we're keen to keep it and to introduce this functionality, I think the label needs updating; "Deployments" make it seem like you're filtering deployments when you're really filtering out flows that have / don't have deployments, which i don't think is altogether clear

**Comment by pleek91** [comment]
Oh weird, I assumed when we reverted this in cloud we also revered it in OSS. That feels very off if I upgrade from server to cloud and now my flows page is significantly different.

**Comment by zhen0** [comment]
@brandonreid - do we still intend to make this happen?  Or should we close this PR?

**Comment by brandonreid** [comment]
> @brandonreid - do we still intend to make this happen? Or should we close this PR?

Let's close it. We've got plans to combine the two versions into one better one. 👍

**Pull request closed without merging**
