### PR TITLE
Bugfix: Fix missing flow link in flow run page heading component

### PR DESCRIPTION
**Pull request by znicholasbrown**

### CODE REVIEW

**Review by zhen0 — APPROVED** [review]
🙏

**Review by brandonreid — APPROVED** [review]
Thank you!!

**Comment by znicholasbrown** [comment]
Note: this also contains a fix for the other relation components since they were implicitly relying on a relation class inherited from the flow run list item component, which is not guaranteed to be present and so would cause the components to lose flex styling

**Comment by pleek91** [comment]
Nice. Thanks @znicholasbrown

**Pull request merged**
