### PR TITLE
Chore: Update flow run endpoint to return new TimelineData map type

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Implementation of https://github.com/PrefectHQ/graphs/pull/147

### CODE REVIEW

**Comment by znicholasbrown** [comment]
Added a DNM label to this since it looks like graphs hasn't been released yet - feel free to remove and lmk if this is something I should review, otherwise I'll leave this for @brandonreid

**Comment by pleek91** [comment]
@znicholasbrown right which is why the build is broken 👍

**Comment by zhen0** [comment]
Should this still be labelled as Do Not Merge?  Anything we can do to help us move the PR forward or decide to close it?

**Comment by brandonreid** [comment]
@zhen0 part of the rebrand effort happening now will involve updating the graphs repo and this will finally get merged.

**Pull request merged**
