### PR TITLE
I have made changes to the FlowMenu.vue file to add the functionality…

### PR DESCRIPTION
**Pull request by AmanSal1**
I have made changes to the FlowMenu.vue file to add the functionality of deleting a flow directly from the overflow menu. This allows us to delete the flow from the overflow menu itself, instead of selecting the individual flow and then deleting it. Previously, the delete functionality was designed to delete multiple flows, but now I have implemented a feature to delete a single flow.

This issue is raised in prefect repository :
"#9518 Add "Delete" to the overflow menu for each flow in the list on the flows page"

https://github.com/PrefectHQ/prefect-ui-library/assets/121633121/d5ab8629-cf97-4e26-b725-30c09d1465ea

### CODE REVIEW

**Comment by pleek91** [comment]
@AmanSal1 Thanks! This looks good to me. The only thing I'm seeing is looks like the file needs to be linted. Would you mind running `npm run lint:fix`? Then I think this is good to go.

**Comment by AmanSal1** [comment]
@pleek91  I have executed the command 'npm run lint:fix' in the Prefect UI library and have added a new commit. Could you please review it?

**Comment by pleek91** [comment]
@AmanSal1 the linting looks good! But it looks like a change was made to the package.json and package-lock.json. Can you please revert/remove those changes? Then I think this is ready to go!

**Review by pleek91 — APPROVED** [review]

**Comment by AmanSal1** [comment]
@pleek91 Sounds great!!

**Pull request merged**
