### PR TITLE
Enhancement: Add options to the deployment tags select

### PR DESCRIPTION
**Pull request by zhen0**
Before:
image

After:

image

Closes https://github.com/PrefectHQ/prefect/issues/9272 
Closes https://github.com/PrefectHQ/prefect/issues/8791

### CODE REVIEW

**Comment by pleek91** [comment]
@zhen0 I like this. Thoughts on moving all the logic into a DeploymentTags component? Also, @znicholasbrown thoughts on this with the work your doing for flows/deployments?

**Comment by znicholasbrown** [comment]
We can try to support this in the new page as well but this work won't be used in the new page as-is

**Comment by zhen0** [comment]
Good point about @znicholasbrown's work.  Hopefully we can still keep the functionality even if we don't keep the code. 

Since any component will be obsolete after Nicholas's updates, are you ok to keep without creating a new component @pleek91?

**Comment by MattDelac** [comment]
@taylor-curran that's an old page "Deployment". Now all the deployments are under the "Flow" page
image

**Pull request merged**
